### PR TITLE
new change 10/05 v2

### PR DESCRIPTION
**Pull request by ericlam1995**
change component, service and models

### CODE REVIEW

**Comment by fhb4061** [comment]
Hi Eric, can please put a description of what you've done here please.

**Comment by fhb4061** [comment]
Bullet points will do

**Comment by ericlam1995** [comment]
Description:

- Component: created message-list, message-form, message-item
- Service: created diagramflow service to connect diagramflow.
- Models: create class message and constructor.
- all css change to scss by manual.

**Comment by fhb4061** [comment]
Okay great, I'm just having a look at it to see whats happening. Thanks for that Eric!

**Comment by fhb4061** [comment]
Make sure you add a description to all of the future pull requests. Does the code work?

**Comment by ericlam1995** [comment]
got it. It should be. If there is an error occured, let me know and I will sort it out.

**Comment by ericlam1995** [comment]
Updated 15/05
change:
- diagramflow service has been modified and fixed.
- message-form will automatically scroll down once the message items add below
- add statement if the message input is empty before sending message.
- replace res.result.fulfillment.speech to res.result.speech.

**Pull request merged**
